---
- name: Copy Nginx conf
  copy:
    src: "{{ config_source }}"
    dest: "{{ config_destination }}"
    owner: root
    group: root

- name: Start Nginx service
  service:
    name: "{{ service_name }}"
    state: started
